spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: MyPassword!
  jpa:
    show-sql: true
  jwt:
    secret:  ${JWT_SECRET:W+ptkkoSFguUac5JraK5tBOXy0s3J9ktfiLMQj59fdM=}